TOP_LEGIT_DOMAINS = [
    "google.com", "youtube.com", "facebook.com", "instagram.com", "twitter.com",
    "x.com", "wikipedia.org", "amazon.com", "yahoo.com", "reddit.com",
    "linkedin.com", "netflix.com", "microsoft.com", "apple.com", "live.com",
    "office.com", "bing.com", "whatsapp.com", "tiktok.com", "pinterest.com",
    "wordpress.com", "blogspot.com", "ebay.com", "adobe.com", "github.com",
    "stackoverflow.com", "dropbox.com", "spotify.com", "zoom.us", "paypal.com",
    "salesforce.com", "wikihow.com", "imdb.com", "cnn.com", "bbc.com",
    "nytimes.com", "forbes.com", "espn.com", "indeed.com", "quora.com",
    "medium.com", "tumblr.com", "vimeo.com", "imgur.com", "craigslist.org",
    "booking.com", "tripadvisor.com", "etsy.com", "walmart.com", "target.com",
    "bestbuy.com", "homedepot.com", "costco.com", "ikea.com", "chase.com",
    "bankofamerica.com", "wellsfargo.com", "citibank.com", "americanexpress.com",
    "discover.com", "capitalone.com", "hsbc.com", "irs.gov", "usa.gov",
    "weather.com", "nasa.gov", "who.int", "un.org", "harvard.edu",
    "mit.edu", "stanford.edu", "berkeley.edu", "coursera.org", "udemy.com",
    "khanacademy.org", "duolingo.com", "steamcommunity.com", "steampowered.com",
    "epicgames.com", "roblox.com", "discord.com", "slack.com", "trello.com",
    "notion.so", "figma.com", "canva.com", "shopify.com", "wix.com",
    "squarespace.com", "godaddy.com", "namecheap.com", "cloudflare.com",
    "digitalocean.com", "heroku.com", "vercel.com", "netlify.com", "npmjs.com",
    "python.org", "mozilla.org", "w3.org", "ietf.org", "archive.org",
    "wikimedia.org", "wiktionary.org", "wikibooks.org", "wikiquote.org",
    "samsung.com", "sony.com", "lg.com", "dell.com", "hp.com",
    "lenovo.com", "intel.com", "amd.com", "nvidia.com", "oracle.com",
    "ibm.com", "sap.com", "cisco.com", "vmware.com", "redhat.com",
    "ubuntu.com", "debian.org", "gnu.org", "kernel.org", "mysql.com",
    "postgresql.org", "mongodb.com", "redis.io", "docker.com", "kubernetes.io",
    "uber.com", "lyft.com", "airbnb.com", "expedia.com", "kayak.com",
    "hulu.com", "disneyplus.com", "hbomax.com", "peacocktv.com", "crunchyroll.com",
    "twitch.tv", "soundcloud.com", "bandcamp.com", "last.fm", "genius.com",
    "yelp.com", "glassdoor.com", "monster.com", "ziprecruiter.com", "upwork.com",
    "fiverr.com", "freelancer.com", "patreon.com", "kickstarter.com", "gofundme.com",
    "change.org", "mailchimp.com", "hubspot.com", "zendesk.com", "intercom.com",
    "atlassian.com", "jira.com", "asana.com", "monday.com", "airtable.com",
    "evernote.com", "onenote.com", "grammarly.com", "duckduckgo.com", "baidu.com",
    "yandex.com", "alibaba.com", "aliexpress.com", "rakuten.com", "shopee.com",
    "lazada.com", "flipkart.com", "myntra.com", "zomato.com", "swiggy.com",
    "uber.com", "ola.com", "irctc.co.in", "gov.uk", "nhs.uk",
    "europa.eu", "canada.ca", "australia.gov.au", "gc.ca", "nih.gov",
    "cdc.gov", "fda.gov", "epa.gov", "energy.gov", "state.gov",
]
